{% set python_min = "3.11" %}
{% set name = "reader" %}
{% set version = "3.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reader-{{ version }}.tar.gz
  sha256: 7e2c3a89e9cac4bf3cbca991b4966a2c48773d4664deaa429ebfc9ec8bcd7f96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - typing_extensions >=4
    - feedparser >=6
    - requests >=2.18
    - werkzeug >2
    - iso8601 >=1
    - beautifulsoup4 >=4.5

test:
  imports:
    - reader
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lemon24/reader
  doc_url: https://reader.readthedocs.io/
  summary: A Python feed reader library.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
