{% set name = "reader" %}
{% set version = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reader-{{ version }}.tar.gz
  sha256: 5ee788184c0a9ee92be4d5e6dac4a4e964d1f99853e9f85d3ccdc495891790f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - typing-extensions >=4
    - feedparser >=6
    - requests >=2.18
    - werkzeug >2
    - iso8601 >=1
    - beautifulsoup4 >=4.5

test:
  imports:
    - reader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lemon24/reader
  doc_url: https://reader.readthedocs.io/
  summary: A Python feed reader library.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
