schema_version: 1

context:
  python_min: "3.11"
  name: reader
  version: "3.26"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/reader-${{ version }}.tar.gz
  sha256: 2b6ad65066f46c35609e047681771632856cb9f82b705e1c9614d83a066f28d9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4
    - feedparser >=6
    - requests >=2.18
    - werkzeug >2
    - beautifulsoup4 >=4.5
    - structlog

tests:
  - python:
      imports:
        - reader
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A Python feed reader library.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/lemon24/reader
  documentation: https://reader.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
